<?php

namespace Database\Seeders;

use App\Models\Institutii;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {

        DB::table('stat_organizare')->insert(
            array(
                ['so_institutie_id'  => 1, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 2, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 3, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 4, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 5, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 6, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 7, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 8, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 9, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 10, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 11, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 12, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 13, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 14, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 15, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 16, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 17, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 18, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 19, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 20, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 21, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 22, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 23, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 24, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 25, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 26, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 27, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 28, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 29, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 30, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 31, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 32, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 33, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 34, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 35, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 36, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 37, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 38, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 39, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 40, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 41, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 42, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 43, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 44, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 45, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 46, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 47, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 48, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 49, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 50, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 51, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 52, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 53, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 54, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 55, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 56, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 57, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 58, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 59, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 60, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 61, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 62, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 63, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 64, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 65, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 66, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 67, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 68, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 69, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 70, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 71, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 72, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 73, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 74, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 75, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 76, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 77, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 78, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 79, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 80, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 81, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 82, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 83, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 84, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 85, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 86, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 87, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 88, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 89, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 90, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 91, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 92, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 93, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 94, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 95, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 96, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 97, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 98, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 99, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 100, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
                ['so_institutie_id'  => 101, 'so_numar_posturi_aprobate' => 1000, 'so_status' => true],
            )
        );
    }
}
